// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sink/v1/sink.proto

// Package rss2msg.sink.v1 defines the gRPC contract spoken by the rss2msg
// "grpc" sink. rss2msg acts as the client: it dials a server you run that
// implements ChangeSink and calls Publish once per detected feed change.
//
// This is the typed analogue of the HTTP/webhook sink. The Change message
// mirrors internal/model.Change field-for-field (schema_version 1).

package sinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChangeSink_Publish_FullMethodName = "/rss2msg.sink.v1.ChangeSink/Publish"
)

// ChangeSinkClient is the client API for ChangeSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChangeSink receives feed changes from rss2msg.
type ChangeSinkClient interface {
	// Publish delivers a single change. A non-OK gRPC status, or an ack with
	// accepted=false, is treated by rss2msg as a delivery failure and drives the
	// configured retry / dead-letter behaviour.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishAck, error)
}

type changeSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeSinkClient(cc grpc.ClientConnInterface) ChangeSinkClient {
	return &changeSinkClient{cc}
}

func (c *changeSinkClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, ChangeSink_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangeSinkServer is the server API for ChangeSink service.
// All implementations must embed UnimplementedChangeSinkServer
// for forward compatibility.
//
// ChangeSink receives feed changes from rss2msg.
type ChangeSinkServer interface {
	// Publish delivers a single change. A non-OK gRPC status, or an ack with
	// accepted=false, is treated by rss2msg as a delivery failure and drives the
	// configured retry / dead-letter behaviour.
	Publish(context.Context, *PublishRequest) (*PublishAck, error)
	mustEmbedUnimplementedChangeSinkServer()
}

// UnimplementedChangeSinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeSinkServer struct{}

func (UnimplementedChangeSinkServer) Publish(context.Context, *PublishRequest) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedChangeSinkServer) mustEmbedUnimplementedChangeSinkServer() {}
func (UnimplementedChangeSinkServer) testEmbeddedByValue()                    {}

// UnsafeChangeSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeSinkServer will
// result in compilation errors.
type UnsafeChangeSinkServer interface {
	mustEmbedUnimplementedChangeSinkServer()
}

func RegisterChangeSinkServer(s grpc.ServiceRegistrar, srv ChangeSinkServer) {
	// If the following call panics, it indicates UnimplementedChangeSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeSink_ServiceDesc, srv)
}

func _ChangeSink_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeSinkServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeSink_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeSinkServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangeSink_ServiceDesc is the grpc.ServiceDesc for ChangeSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rss2msg.sink.v1.ChangeSink",
	HandlerType: (*ChangeSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _ChangeSink_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sink/v1/sink.proto",
}
