// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sink/v1/sink.proto

// Package rss2msg.sink.v1 defines the gRPC contract spoken by the rss2msg
// "grpc" sink. rss2msg acts as the client: it dials a server you run that
// implements ChangeSink and calls Publish once per detected feed change.
//
// This is the typed analogue of the HTTP/webhook sink. The Change message
// mirrors internal/model.Change field-for-field (schema_version 1).

package sinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest carries one change.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        *Change                `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_sink_v1_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sink_v1_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_sink_v1_sink_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

// PublishAck reports the outcome of a Publish call. An OK status with an empty
// ack (accepted defaulting to false but no error) is ambiguous, so servers
// SHOULD set accepted=true on success; rss2msg treats accepted=false as a
// failure.
type PublishAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Optional human-readable reason when accepted=false; surfaced in rss2msg logs.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_sink_v1_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_sink_v1_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_sink_v1_sink_proto_rawDescGZIP(), []int{1}
}

func (x *PublishAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PublishAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Change mirrors internal/model.Change. Optional model fields map to proto3
// default-value semantics; the *time.Time fields map to absent Timestamps.
type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	FeedUrl       string                 `protobuf:"bytes,2,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	FeedTitle     string                 `protobuf:"bytes,3,opt,name=feed_title,json=feedTitle,proto3" json:"feed_title,omitempty"`
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// kind is "new" or "updated".
	Kind       string   `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Title      string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Link       string   `protobuf:"bytes,7,opt,name=link,proto3" json:"link,omitempty"`
	Authors    []string `protobuf:"bytes,8,rep,name=authors,proto3" json:"authors,omitempty"`
	Summary    string   `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	Content    string   `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Categories []string `protobuf:"bytes,11,rep,name=categories,proto3" json:"categories,omitempty"`
	// published_at / updated_at are absent when the source omitted them.
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ContentHash string                 `protobuf:"bytes,14,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	DetectedAt  *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	// dlq_* are populated only when this change is delivered to a dead-letter sink.
	DlqFromSink   string `protobuf:"bytes,16,opt,name=dlq_from_sink,json=dlqFromSink,proto3" json:"dlq_from_sink,omitempty"`
	DlqError      string `protobuf:"bytes,17,opt,name=dlq_error,json=dlqError,proto3" json:"dlq_error,omitempty"`
	DlqAttempts   int32  `protobuf:"varint,18,opt,name=dlq_attempts,json=dlqAttempts,proto3" json:"dlq_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_sink_v1_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_sink_v1_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_sink_v1_sink_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Change) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *Change) GetFeedTitle() string {
	if x != nil {
		return x.FeedTitle
	}
	return ""
}

func (x *Change) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Change) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Change) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Change) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Change) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Change) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Change) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Change) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Change) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Change) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Change) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Change) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *Change) GetDlqFromSink() string {
	if x != nil {
		return x.DlqFromSink
	}
	return ""
}

func (x *Change) GetDlqError() string {
	if x != nil {
		return x.DlqError
	}
	return ""
}

func (x *Change) GetDlqAttempts() int32 {
	if x != nil {
		return x.DlqAttempts
	}
	return 0
}

var File_sink_v1_sink_proto protoreflect.FileDescriptor

const file_sink_v1_sink_proto_rawDesc = "" +
	"\n" +
	"\x12sink/v1/sink.proto\x12\x0frss2msg.sink.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x0ePublishRequest\x12/\n" +
	"\x06change\x18\x01 \x01(\v2\x17.rss2msg.sink.v1.ChangeR\x06change\">\n" +
	"\n" +
	"PublishAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xec\x04\n" +
	"\x06Change\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\bfeed_url\x18\x02 \x01(\tR\afeedUrl\x12\x1d\n" +
	"\n" +
	"feed_title\x18\x03 \x01(\tR\tfeedTitle\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04link\x18\a \x01(\tR\x04link\x12\x18\n" +
	"\aauthors\x18\b \x03(\tR\aauthors\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"categories\x18\v \x03(\tR\n" +
	"categories\x12=\n" +
	"\fpublished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fcontent_hash\x18\x0e \x01(\tR\vcontentHash\x12;\n" +
	"\vdetected_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12\"\n" +
	"\rdlq_from_sink\x18\x10 \x01(\tR\vdlqFromSink\x12\x1b\n" +
	"\tdlq_error\x18\x11 \x01(\tR\bdlqError\x12!\n" +
	"\fdlq_attempts\x18\x12 \x01(\x05R\vdlqAttempts2U\n" +
	"\n" +
	"ChangeSink\x12G\n" +
	"\aPublish\x12\x1f.rss2msg.sink.v1.PublishRequest\x1a\x1b.rss2msg.sink.v1.PublishAckB0Z.github.com/iambod/rss2msg/proto/sink/v1;sinkv1b\x06proto3"

var (
	file_sink_v1_sink_proto_rawDescOnce sync.Once
	file_sink_v1_sink_proto_rawDescData []byte
)

func file_sink_v1_sink_proto_rawDescGZIP() []byte {
	file_sink_v1_sink_proto_rawDescOnce.Do(func() {
		file_sink_v1_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sink_v1_sink_proto_rawDesc), len(file_sink_v1_sink_proto_rawDesc)))
	})
	return file_sink_v1_sink_proto_rawDescData
}

var file_sink_v1_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sink_v1_sink_proto_goTypes = []any{
	(*PublishRequest)(nil),        // 0: rss2msg.sink.v1.PublishRequest
	(*PublishAck)(nil),            // 1: rss2msg.sink.v1.PublishAck
	(*Change)(nil),                // 2: rss2msg.sink.v1.Change
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sink_v1_sink_proto_depIdxs = []int32{
	2, // 0: rss2msg.sink.v1.PublishRequest.change:type_name -> rss2msg.sink.v1.Change
	3, // 1: rss2msg.sink.v1.Change.published_at:type_name -> google.protobuf.Timestamp
	3, // 2: rss2msg.sink.v1.Change.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: rss2msg.sink.v1.Change.detected_at:type_name -> google.protobuf.Timestamp
	0, // 4: rss2msg.sink.v1.ChangeSink.Publish:input_type -> rss2msg.sink.v1.PublishRequest
	1, // 5: rss2msg.sink.v1.ChangeSink.Publish:output_type -> rss2msg.sink.v1.PublishAck
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sink_v1_sink_proto_init() }
func file_sink_v1_sink_proto_init() {
	if File_sink_v1_sink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sink_v1_sink_proto_rawDesc), len(file_sink_v1_sink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sink_v1_sink_proto_goTypes,
		DependencyIndexes: file_sink_v1_sink_proto_depIdxs,
		MessageInfos:      file_sink_v1_sink_proto_msgTypes,
	}.Build()
	File_sink_v1_sink_proto = out.File
	file_sink_v1_sink_proto_goTypes = nil
	file_sink_v1_sink_proto_depIdxs = nil
}
